### ISSUE TITLE
Please clarify package installation instructions

### ISSUE THREAD

**Issue by dmartintucker** [blagae/open_words#1]
Attempts to get this package to work for me have been unsuccessful.

As no installation guide was included, I tried installing with the following command:
`pip install git+https://github.com/blagae/open_words.git#egg=open_words`

This resulted in a successful install, but any attempts to use the `parse` module _**exactly as shown in the readme**_ result in this error

`>>>from open_words.parse import Parser`
`>>>ModuleNotFoundError: No module named 'open_words.parse`

However, simply running this works
`>>>import open_words`

Any clarification on how to properly install this package would be greatly appreciated.

**Comment by blagae** [comment]
Hi,

From the `>>>` lines, I assume you are installing the package on the command line. Have you tried this in a more structured environment than the IDLE ?
I am not an expert on Python package building and I never tested if it works on the command line. It does (or has the potential to) work if you use it as a dependency in a virtualenv.

Anyway, I will look into fixing this, but I can't promise anything soon.

**Comment by blagae** [comment]
Hi @dmartintucker 

I decided to look into it asap anyway, and it turned out that my setup worked because of some egg magic in my IDE. I moved the logic to generate the `open_words.files` package to the install procedure, which fixes the surface issue on `open_words.parse` for me.
This works for me on the command line, so please test again to verify that it's OK for you now.

**Comment by blagae** [comment]
Please refer to https://github.com/blagae/whitakers_words for future issues and/or pull requests.

**Comment by dmartintucker** [comment]
Hi @blagae, thanks for responding and for looking into this! I'll test this again and let you know how things go.
