### ISSUE TITLE
Add declension groups

### ISSUE THREAD

**Issue by CodyTeague** [blagae/open_words#3]
Recreation of https://github.com/ArchimedesDigital/open_words/issues/12 for this repository

Original text:
> Adding declension group number (1st, 2nd, ..., 5th) into the "infls" attributes would be a great improvement, as it is the most useful part of the original words.

**Comment by blagae** [comment]
Hi,

I have tentatively added support for this, adding the "decl" key under "infls" for regular nominal and verbal forms. If the value is 6 or higher, which indicates irregular forms such as ire (eo), edere, etc. in Whitaker's original list, then the key is not added to the "infls" dictionary. Below is the current return value for "arma", please let me know if this is satisfactory:

	{
	  "word": "arma",
	  "defs": [
		{
		  "orth": [
			"arm",
			"arm"
		  ],
		  "senses": [
			"arms (pl.), weapons, armor, shield",
			"close fighting weapons",
			"equipment",
			"force"
		  ],
		  "infls": [
			{
			  "stem": "arm",
			  "ending": "a",
			  "pos": "noun",
			  "form": {
				"case": "nominative",
				"number": "plural",
				"gender": "neuter"
			  },
			  "decl": 2
			},
			{
			  "stem": "arm",
			  "ending": "a",
			  "pos": "noun",
			  "form": {
				"case": "vocative",
				"number": "plural",
				"gender": "neuter"
			  },
			  "decl": 2
			},
			{
			  "stem": "arm",
			  "ending": "a",
			  "pos": "noun",
			  "form": {
				"case": "accusative",
				"number": "plural",
				"gender": "neuter"
			  },
			  "decl": 2
			}
		  ]
		},
		{
		  "orth": [
			"arm",
			"arm",
			"armav",
			"armat"
		  ],
		  "senses": [
			"equip, fit with armor",
			"arm",
			"strengthen",
			"rouse, stir",
			"incite war",
			"rig (ship)"
		  ],
		  "infls": [
			{
			  "stem": "arm",
			  "ending": "a",
			  "pos": "verb",
			  "form": {
				"tense": "present",
				"voice": "active",
				"mood": "imperative",
				"person": 2,
				"number": "singular"
			  },
			  "decl": 1
			}
		  ]
		}
	  ]
	}

**Comment by CodyTeague** [comment]
@blagae , looks good. Thank you so much!

**Comment by fsvehla** [comment]
@blagae Was this commited to master? I can’t get it work either in this repo, or the new one.

**Comment by blagae** [comment]
It should be in there, yes, at least in the new repo. I can check tomorrow, and if it isn't in there I'll add it then. In general, I recommend that you use the new project because it has seen a lot of development that isn't available here.

**Comment by blagae** [comment]
Hi @fsvehla I just tried on [the new repo](https://github.com/blagae/whitakers_words) and I found that the information is available there, under the result dict's entry "category":

```
$ whitaker parse conderet
{
    "text": "conderet",
    "forms": [
        {
            "text": "conderet",
            "analyses": {
                "12238": {
                    "lexeme": {
                        "id": 12238,
                        "category": [
                            3,
                            1
                        ],
                        <etc>
```

If you can't get this result, then I have to assume that something is wrong with your setup. This may mean that my setup instructions are unclear or incomplete, in which case I'll gladly accept feedback on improving the information in the README file.
